alias f="cat"
alias goo="goose"
alias rw="railway"
alias wr="wrangler"
alias b="bun"
alias n="nvim"
alias cc="claude"
alias cx="codex --yolo"
alias c="claude --dangerously-skip-permissions"
alias ccp="claude --permission-mode plan"
alias p="pnpm"
alias sp="git diff main --cached --name-only -z --diff-filter=ACMR | grep -z -E '\\.(ts|tsx|js|jsx|json|css|md)$' | xargs -0 bunx prettier --write && git diff main --cached --name-only -z --diff-filter=ACMR | grep -z -E '\\.(ts|tsx|js|jsx)$' | xargs -0 env NODE_OPTIONS=--max-old-space-size=8192 eslint --fix"
alias y="yazi"
alias lg="lazygit"
alias ob="obsidian"
