local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("f.", { t("<%= form."), i(1), t(" %>") }),
  s("R.", { t("Rails.") }),
  s("a.", { t("application.") }),
  s("c.", { t("credentials.") }),
  s("r.", { t("routes.") }),
  s("u_", { t("url_helpers") }),
  s("c_", { t("card_") }),
  s("t_", { t("tooltip_") }),
  s("p_", { t("popover_") }),
  s("lb_", { t("listbox_") }),
  s("dr_", { t("dropdown_") }),
  s("d_", { t("dialog_") }),
  s("r_", { t("render_") }),
  s("rl", { t("render_link_to ") }),
  s("rb", { t("render_button_to ") }),
  s("lt", { t("link_to ") }),
  s("bt", { t("button_to ") }),
  s("tsf", { t("turbo_stream_from ") }),
  s("rd", { t("render ") }),
  s("rp", { t("render partial: ") }),
  s("rf", { t("render_form_with") }),
  s("fw", { t("form_with ") }),
  s("cf", { t("content_for") }),
  s("c:", { t('class: "'), i(1), t('"') }),
  s("c=", { t('class="'), i(1), t('"') }),
  s("dv", { t("data-"), i(1), t('-value="'), i(2), t('"') }),
  s("dt", { t("data-"), i(1), t('-target="'), i(2), t('"') }),
  s("dn", { t('data-action="'), i(1), t('"') }),
  s("d;", { t("<% "), i(1), t(" do %>"), t({ "", "<% end %>" }) }),
  s("f;", { t("<%= "), i(1), t(" do %>"), t({ "", "<% end %>" }) }),
  s("c;", { t("<%= "), i(1), t(" do |"), i(2), t("| %>"), t({ "", "<% end %>" }) }),
  s("a;", { t("<% "), i(1), t({ " %>" }) }),
  s("s;", { t("<%= "), i(1), t({ " %>" }) }),
  s("fi ", { t("<% if "), i(1), t({ " %>", "<% end %>" }) }),
  s("dc", { t('data-controller="'), i(1), t('"') }),
  s("h1.", { t('<h1 class="'), i(1), t('">'), i(2), t("</h1>") }),
  s("h2.", { t('<h2 class="'), i(1), t('">'), i(2), t("</h2>") }),
  s("h3.", { t('<h3 class="'), i(1), t('">'), i(2), t("</h3>") }),
  s("h4.", { t('<h4 class="'), i(1), t('">'), i(2), t("</h4>") }),
  s("tbl", { t({ '<table class="table">', "  " }), i(1), t({ "", "</table>" }) }),
  s("sl,", { t({ '<select class="select" ' }), i(1), t({ ">", "</select>" }) }),
  s("tr.", { t('<tr class="'), i(1), t('">'), i(2), t("</tr>") }),
  s("th.", { t('<th class="'), i(1), t('">'), i(2), t("</th>") }),
  s("td.", { t('<td class="'), i(1), t('">'), i(2), t("</td>") }),
  s("l,", { t('<label class="label" htmlFor="'), i(1), t('">'), i(2), t("</label>") }),
  s("d.", { t('<div class="'), i(1), t('">'), i(2), t("</div>") }),
  s("dl.", { t('<dl class="'), i(1), t('">'), i(2), t("</dl>") }),
  s("dt.", { t('<dt class="'), i(1), t('">'), i(2), t("</dt>") }),
  s("dd.", { t('<dd class="'), i(1), t('">'), i(2), t("</dd>") }),
  s("fr.", { t('<form class="'), i(1), t('">'), i(2), t("</form>") }),
  s("b.", { t('<button class="'), i(1), t('">'), i(2), t("</button>") }),
  s("s.", { t('<span class="'), i(1), t('">'), i(2), t("</span>") }),
  s("p.", { t('<p class="'), i(1), t('">'), i(2), t("</p>") }),
  s("s.", { t("style={styles."), i(1), t("}") }),
  s("it.", { t('<input type="text" class="'), i(1), t('" />') }),
}
